import type { NextPage } from 'next'
import Head from 'next/head'
import { Navbar } from '../components'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Rainbow Trunk - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Navbar />
      <main className='mt-14'>
        <h1>Hello World!</h1>
      </main>
    </div>
  )
}

export default Home
